POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "id": "54a8746e-34c4-4cf4-bf72-bfecd039be9a",
    "date": "2020-03-01",
    "specialist": "Dr Apartment",
    "type": "HealthCheck",
    "description": "Too much cat bites.",
    "healthCheckRating": 0
}