POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Chuck",
    "name": "Chuck",
    "password": "admin"
}

#   title: String,
#   author: String,
#   url: String,
#   likes: Number,