PUT http://localhost:3001/api/blogs/6802919b710ae4b60790e2b9
Content-Type: application/json

{
    "title": "First dawn",
    "author": "Rasha",
    "url": "https://www.dawnspear.com/2002",
    "likes": 33,
    "user": "68028f229dec78e72c5acaa5",
    "id": "6802919b710ae4b60790e2b9"
}

# {
#     "title": "First dawn",
#     "author": "Rasha",
#     "url": "https://www.dawnspear.com/2002",
#     "likes": 32,
#     "user": {
#         "username": "Roze",
#         "name": "Rosalaen",
#         "id": "68028f229dec78e72c5acaa5"
#     },
#     "id": "6802919b710ae4b60790e2b9"
# }

#   title: String,
#   author: String,
#   url: String,
#   likes: Number,