POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "How to raise a dragoon",
    "author": "Natasha Rockstone",
    "url": "https://www.dragonsarecool.com",
    "likes": 8823
}

#   title: String,
#   author: String,
#   url: String,
#   likes: Number,