POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Second dawn",
    "author": "Rasha",
    "url": "https://www.dawnspear.com/2002",
    "likes": 32,
    "userId": "68028f229dec78e72c5acaa5"
}

#   title: String,
#   author: String,
#   url: String,
#   likes: Number,