POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Ro",
    "name": "Rosalaen",
    "password": "ad"
}

#   title: String,
#   author: String,
#   url: String,
#   likes: Number,